Repository provenance-io/p8e-cee-api, pull requests merged in 2022-09, with the labels that each got.

#56 Update classpath models to latest versions (MAM to v0.1.13, contracts to v0.5.0)
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: patch, dependencies

#57 Updating Asset Classification / internal endpoints
  buildSrc/src/main/kotlin/Dependencies.kt
  dc.sh
  models/src/main/kotlin/io/provenance/api/models/p8e/contracts/SmartContractConfig.kt
  models/src/main/kotlin/io/provenance/api/models/p8e/contracts/VerifyAssetRequest.kt
  service/docker/prov-init/contracts/asset_definitions.json
  service/src/main/kotlin/io/provenance/api/domain/provenance/Provenance.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/contracts/classify/ClassifyAsset.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/contracts/common/AssetClassficationUtils.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/contracts/definitions/GetAssetDefinitions.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/contracts/definitions/models/GetAssetDefinitionsRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/contracts/fees/GetFeesForAsset.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/contracts/status/GetClassificationStatus.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/contracts/status/models/GetStatusOfClassificationRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/contracts/verify/VerifyAsset.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/ProvenanceService.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceHandler.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/internal/provenance/InternalProvenanceApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/internal/provenance/InternalProvenanceHandler.kt
Labels: enhancement

#58 Cleaning up provenance service
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/ProvenanceService.kt
Labels: patch, fix

#59 Update contracts classpath model to latest versions v0.5.1
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: patch, dependencies

#60 Add endpoint for scope ownership modification
  models/src/main/kotlin/io/provenance/api/models/p8e/tx/ChangeScopeOwnershipRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/account/GetSigner.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/create/CreateTx.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/scope/ChangeScopeOwnership.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/scope/models/ChangeScopeOwnershipRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/ProvenanceService.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/extensions/ProvenanceExtensions.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/extensions/TxBodyExtensions.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/utility/ProvenanceUtils.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceHandler.kt
  service/src/test/kotlin/io/provenance/api/integration/base/IntegrationTestBase.kt
  service/src/test/kotlin/io/provenance/api/integration/tx/ChangeScopeOwnershipTest.kt
Labels: minor, feature

#62 Upping Metadata-asset-model Version
  .github/workflows/build.yml
  .github/workflows/release.yml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: patch, dependencies

#64 File Part Byte Issue
  service/src/main/kotlin/io/provenance/api/util/MultiPartExtensions.kt
Labels: bug, patch
