Repository provenance-io/p8e-cee-api, pull requests merged in 2022-06, with the labels that each got.

#35 Fixing release versioning
  .github/workflows/release.yml
Labels: bug

#36 Update loan package, protobuf, key access lib, & Kotest versions to latest
  buildSrc/src/main/kotlin/Dependencies.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/common/originator/EntityManager.kt
Labels: minor, dependencies

#39 Allow for supplying contracts version due to removal of semver plugin
  dc.sh
Labels: bug, patch
