Repository provenance-io/p8e-cee-api, pull requests merged in 2022-07, with the labels that each got.

#45 Add note about what p8e-cee-api means
  README.md
Labels: patch, docs

#47 Adding keys
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/common/ContractUtilities.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/common/client/CreateClient.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/execute/ExecuteContract.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/common/originator/EntityManager.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/common/originator/models/KeyManagementConfigWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/get/RetrieveAndDecrypt.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/StoreFile.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/StoreProto.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/account/GetSigner.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/ProvenanceService.kt
  service/src/test/kotlin/io/provenance/api/domain/usecase/objectstore/StoreAssetTest.kt
  service/src/test/kotlin/io/provenance/api/domain/usecase/provenance/tx/CreateTxTest.kt
Labels: enhancement, minor

#48 Removing Custom Sequence Tracking
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/CachedAccountSequence.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/ProvenanceService.kt
Labels: enhancement, patch

#49 Readding Offset Handling
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/CachedAccountSequence.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/ProvenanceService.kt
Labels: enhancement, patch
