Repository provenance-io/p8e-cee-api, pull requests merged in 2023-01, with the labels that each got.

#82 Object store v2
  buildSrc/src/main/kotlin/Dependencies.kt
  models/src/main/kotlin/io/provenance/api/models/eos/store/StoreObjectResponse.kt
  models/src/main/kotlin/io/provenance/api/models/p8e/tx/permissions/dataAccess/UpdateScopeDataAccessRequest.kt
  service/build.gradle.kts
  service/docker/dependencies.yaml
  service/src/main/kotlin/io/provenance/api/domain/objectStore/ObjectStore.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/get/GetFile.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/get/GetObject.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/get/GetProto.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/get/models/GetFileRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/get/models/GetProtoRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/get/models/RetrieveAndDecryptRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/replication/EnableReplication.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/CreateGatewayJwt.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/StoreFile.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/StoreObject.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/StoreProto.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/models/CreateGatewayJwtRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/models/StoreFileRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/models/StoreObjectRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/models/StoreProtoRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/permissions/dataAccess/UpdateScopeDataAccess.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/permissions/dataAccess/models/UpdateScopeDataAccessRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/frameworks/config/AppConfig.kt
  service/src/main/kotlin/io/provenance/api/frameworks/config/ObjectStoreProperties.kt
  service/src/main/kotlin/io/provenance/api/frameworks/objectStore/ObjectStoreService.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/Routes.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/objectStore/ObjectStoreApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/objectStore/ObjectStoreHandler.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/internal/objectStore/InternalObjectStoreApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/internal/objectStore/InternalObjectStoreHandler.kt
  service/src/main/kotlin/io/provenance/api/util/ObjectStoreGatewayExt.kt
  service/src/test/kotlin/io/provenance/api/domain/usecase/objectstore/EnableReplicationTest.kt
  service/src/test/kotlin/io/provenance/api/domain/usecase/objectstore/StoreAssetTest.kt
Labels: enhancement, minor, feature

#84 OS gateway object registration / revokation
  buildSrc/src/main/kotlin/Dependencies.kt
  models/src/main/kotlin/io/provenance/api/models/eos/permissions/RegisterObjectAccessRequest.kt
  models/src/main/kotlin/io/provenance/api/models/eos/permissions/RegisterScopeObjectsAccessRequest.kt
  models/src/main/kotlin/io/provenance/api/models/eos/permissions/RevokeObjectAccessRequest.kt
  models/src/main/kotlin/io/provenance/api/models/eos/permissions/RevokeScopeObjectsAccessRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/permissions/RegisterObjectAccess.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/permissions/RegisterScopeObjectsAccess.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/permissions/RevokeObjectAccess.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/permissions/RevokeScopeObjectsAccess.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/permissions/model/RegisterObjectAccessRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/permissions/model/RegisterScopeObjectsAccessRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/permissions/model/RevokeObjectAccessRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/permissions/model/RevokeScopeObjectsAccessRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/objectStore/ObjectStoreApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/objectStore/ObjectStoreHandler.kt
Labels: enhancement, feature

#86 Updating batch endpoints
  models/src/main/kotlin/io/provenance/api/models/cee/approve/ApproveContractExecutionBatchResponse.kt
  models/src/main/kotlin/io/provenance/api/models/cee/approve/ApproveContractExecutionResponse.kt
  models/src/main/kotlin/io/provenance/api/models/cee/execute/ContractExecutionResponse.kt
  models/src/main/kotlin/io/provenance/api/models/cee/submit/SubmitContractBatchExecutionResultResponse.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/approve/ApproveContractBatchExecution.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/approve/ApproveContractExecution.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/execute/ExecuteContract.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/execute/ExecuteContractBatch.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/submit/SubmitContractBatchExecutionResult.kt
Labels: enhancement, feature

#88 Add JsonTypeInfo to sealed class
  models/src/main/kotlin/io/provenance/api/models/cee/execute/ContractExecutionResponse.kt
  models/src/main/kotlin/io/provenance/api/models/cee/execute/ExecuteContractBatchRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/execute/ExecuteContractBatch.kt
  service/src/main/resources/application-local.properties
Labels: patch, fix

#89 Add support for prerelease of Docker images, fix other minutiae
  .github/workflows/release.yml
  models/src/main/kotlin/io/provenance/api/models/cee/execute/ExecuteContractRequest.kt
Labels: patch, chore

#91 Fix Maven publishing not occurring on release events
  .github/workflows/release.yml
Labels: patch, chore

#92 Tx timeout height standardization
  service/src/main/kotlin/io/provenance/api/domain/provenance/Provenance.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/approve/ApproveContractBatchExecution.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/approve/ApproveContractExecution.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/execute/ExecuteContract.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/execute/ExecuteContractBatch.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/submit/SubmitContractBatchExecutionResult.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/submit/SubmitContractExecutionResult.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/account/GetSigner.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/create/CreateTx.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/create/models/CreateTxRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/execute/ExecuteTx.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/permissions/authz/UpdateAuthzGrant.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/permissions/dataAccess/UpdateScopeDataAccess.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/scope/ChangeScopeOwnership.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/ProvenanceService.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/extensions/ProvenanceExtensions.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/extensions/TxBodyExtensions.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/utility/ProvenanceUtils.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceHandler.kt
  service/src/test/kotlin/io/provenance/api/domain/usecase/provenance/tx/CreateTxTest.kt
Labels: enhancement, minor, chore

#94 Scope ownership endpoint updates
  models/src/main/kotlin/io/provenance/api/models/p8e/tx/ChangeScopeOwnershipBatchRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/scope/ChangeScopeOwnership.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/scope/models/ChangeScopeOwnershipBatchRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/tx/scope/models/ChangeScopeOwnershipRequestWrapper.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceApi.kt
  service/src/main/kotlin/io/provenance/api/frameworks/web/external/provenance/ProvenanceHandler.kt
  service/src/test/kotlin/io/provenance/api/integration/tx/ChangeScopeOwnershipTest.kt
Labels: enhancement, feature

#95 Updating release to allow maven to publish
  .github/workflows/release.yml
Labels: bug

#96 Update build.yml linting
  .github/workflows/build.yml
Labels: chore

#97 broadcast adjustments, synchronizing tx
  models/src/main/kotlin/io/provenance/api/models/p8e/ProvenanceConfig.kt
  service/src/main/kotlin/io/provenance/api/frameworks/provenance/ProvenanceService.kt
Labels: patch, chore

#98 classification libs 3.6.1
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: patch, dependencies

#99 Key Access Lib updates
  buildSrc/src/main/kotlin/Dependencies.kt
  models/build.gradle.kts
  models/src/main/kotlin/io/provenance/api/models/account/KeyManagementConfig.kt
  service/src/main/kotlin/io/provenance/api/domain/cee/ContractService.kt
  service/src/main/kotlin/io/provenance/api/domain/objectStore/ObjectStore.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/cee/common/client/CreateClient.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/common/originator/EntityManager.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/get/GetObject.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/CreateGatewayJwt.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/StoreFile.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/StoreObject.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/StoreProto.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/objectStore/store/models/StoreObjectRequest.kt
  service/src/main/kotlin/io/provenance/api/domain/usecase/provenance/account/GetSigner.kt
  service/src/main/kotlin/io/provenance/api/frameworks/cee/P8eContractService.kt
  service/src/main/kotlin/io/provenance/api/frameworks/objectStore/ObjectStoreService.kt
  service/src/test/kotlin/io/provenance/api/domain/usecase/objectstore/StoreAssetTest.kt
  service/src/test/kotlin/io/provenance/api/integration/objectstore/ObjectStoreSpec.kt
Labels: minor, chore, dependencies
